FROM node:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Expose the port on which your Fastify server runs (change this if needed)
EXPOSE 3000

# Define the command to run your server
CMD ["npm", "start"]  # Replace with the command you use to start your server

